config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'candidates#index'
  devise_for :users
  resources :users

  get '/candidates/autocomplete_candidate_ballot_name'
  get '/candidates' => 'candidates#index'
  get '/candidates/:id' => 'candidates#show', as: 'candidate'

  namespace :api do
    get 'candidates' => 'candidates#index'
    get 'candidates/:candidate_id/campaign_finance_transactions' => 'campaign_finance_transactions#index'
    get 'candidates/:candidate_id/campaign_finance_transactions/:id' => 'campaign_finance_transactions#show'

    namespace :analytics do
      get 'campaign_finance_transactions/amounts_by_state' => 'campaign_finance_transactions#amounts_by_state'
      get 'campaign_finance_transactions/amounts_by_filer' => 'campaign_finance_transactions#amounts_by_filer'
      get 'campaign_finance_transactions/amounts_by_filer_contributor_payee' => 'campaign_finance_transactions#amounts_by_filer_contributor_payee'
    end
  end
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :candidate_filings
  has_many :committees
  has_many :campaign_finance_transactions, through: :committees

  #validates :candidate_source_id, presence: true, numericality: true

  def stats_by_date from_date, to_date
    events_by_date = campaign_finance_transactions.group(:sub_type)
                          .select(:sub_type)
                          .group(:transaction_date)
                          .select(:transaction_date)
                          .sum(:amount)

    types = campaign_finance_transactions.select(:sub_type).uniq.pluck(:sub_type)

    (from_date..to_date).map{ |date|
      {
        date: date,
      }.merge(
        types.reduce(Hash.new) {|hash, type|
          hash[type.to_sym] = events_by_date[[type, date]]
          hash
        }
      )
    }
  end

  def to_s
    ballot_name
  end
end

app/controllers/api/candidates_controller.rb
class Api::CandidatesController < ApplicationController
  def index
    @candidates = Candidate.order(:ballot_name)
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  autocomplete :candidate, :ballot_name

  def index
    #@candidates = Candidate.all
    records_array = ActiveRecord::Base.connection.execute "WITH amount_ranks AS (
      SELECT c.id,
             c.committee_id,
             co.candidate_id,
             c.filer,
             c.contributor_payee,
             c.sub_type,
             c.amount,
             ROW_NUMBER() OVER (ORDER BY c.amount DESC) AS amount_rank
      FROM campaign_finance_transactions c LEFT OUTER JOIN committees co ON c.committee_id = co.id
      WHERE co.candidate_id IS NOT NULL)
    SELECT a.* from amount_ranks a
    WHERE a.amount_rank <= 10"
    @transactions = CampaignFinanceTransaction.where(id: records_array.map{|result| result['id']}).order('amount DESC')
    @candidates = if params[:ballot_name].present?
                    Candidate.where("ballot_name LIKE ?", "%#{params[:ballot_name]}%")
                  else
                    nil
                  end
  end

  def show
    @candidate = Candidate.find(params[:id])
    @candidate_transactions = @candidate.campaign_finance_transactions.order(:transaction_date)
    @transaction_type_summary = @candidate.campaign_finance_transactions.group(:sub_type)
                                          .select(:sub_type)
                                          .sum(:amount)
                                          .sort_by{|k,v| v}
                                          .reverse

    @stats = @candidate.stats_by_date Date.new(2014,8,1), Date.today
    @types = @candidate.campaign_finance_transactions.select(:sub_type).uniq.pluck(:sub_type)

    @stats_for_chart = @types.map{|key|
      {
        key: key,
        values: @stats.map{|v|
            {
              x: v[:date],
              y: v[key.to_sym].to_i
            }
          }
      }
    }
    
    @transaction_type_summary_for_chart = [
      {
        key: 'Transaction Types',
        values: @transaction_type_summary.map{|k,v|
          {
            label: k.blank? ? 'Unknown' : k,
            value: v
          }
        }
      }
      
    ]
    @transaction_type_max_value = @transaction_type_summary.present? ? @transaction_type_summary.first.last : 0

    @state_summary = @candidate.campaign_finance_transactions.group(:state)
                               .select(:state)
                               .sum(:amount)
                               .sort_by{|k,v| v}
                               .reverse

    @state_summary_for_chart = [
      {
        key: 'States',
        values: @state_summary.map{|k,v|
            {
              label: k.blank? ? 'Unknown' : k,
              value: v
            }
          }
      }
    ]

    @state_max_value = @state_summary.present? ? @state_summary.first.last : 0
  end

end

app/views/candidates/index.html.slim
h2 Candidates
h3 Search by Name

.search
  = form_tag('/', method: :get) do
    = autocomplete_field_tag 'ballot_name', '', candidates_autocomplete_candidate_ballot_name_path, :update_elements => {}


- if @candidates
  h3 Results
  table.table.table-bordered.table-hover
    thead
      tr
        th Name
        th Party
        th Election
        th Received Contributions

    tbody
      - @candidates.each do |candidate|
        tr
          td = link_to candidate, candidate_path(candidate)
          td = candidate.party_affiliation
          td = candidate.candidate_filings.order("filed_date DESC").first.election_title
          td = number_to_currency candidate.campaign_finance_transactions.where(sub_type: 'Cash Contribution').sum(:amount)
  br

h3 Top 10 Candidate transactions

table.table.table-bordered.table-hover
  thead
    tr
      th Candidate
      th Date
      th Status
      th Filer
      th Contributor / Payee
      th Type
      th State
      th Amount
      th Aggregate Amount

  tbody
    - @transactions.each do |trans|
      tr
        td = link_to trans.committee.candidate, candidate_path(trans.committee.candidate)
        td = trans.transaction_date
        td = trans.transaction_status
        td = trans.filer
        td = trans.contributor_payee
        td = trans.sub_type
        td = trans.state
        td = number_to_currency trans.amount
        td = number_to_currency trans.aggregate_amount

br

app/views/candidates/show.html.slim
h3 = @candidate.ballot_name
h4 = @candidate.party_affiliation

/h1 Listing hoof_sensor_readings
/
/h2 Search
/= form_for(:hoof_sensor_reading, method: :get, url: hoof_sensor_readings_path, html: {role: 'form'}, defaults: {input_html: {class: "form-control"}}) do |f|
/  .form-inputs
/    label Batch
/    = f.collection_select :batch_id, Batch.all, :id, :track, {include_blank: true, selected: params[:hoof_sensor_reading].try(:[], :batch_id)}
/    = f.button :submit, class: 'btn btn-default'

h4 State Summary

svg.state_summary style='height:500px; width:690px;'

javascript:

  nv.addGraph(function() {
    var data = #{@state_summary_for_chart.to_json.html_safe}
    var chart = nv.models.discreteBarChart()
      .x(function(d) { return d.label })    //Specify the data accessors.
      .y(function(d) { return d.value })
      .yDomain([0, #{@state_max_value}])
      .showValues(true)
      .valueFormat(d3.format('$,f'))
      .margin({top: 30, right: 60, bottom: 50, left: 70})
      .color(d3.scale.category10().range());

    chart.yAxis.axisLabel("Amount")
      .tickFormat(d3.format('$,f'));


    d3.select('svg.state_summary')
      .datum(data)
      .transition().duration(500)
      .call(chart);

    nv.utils.windowResize(chart.update);

    return chart;
  });


h4 Transactions Type Summary

svg.transaction_type style='height:500px; width:690px;'

javascript:

  nv.addGraph(function() {
    var data = #{@transaction_type_summary_for_chart.to_json.html_safe}
    var chart = nv.models.discreteBarChart()
      .x(function(d) { return d.label })    //Specify the data accessors.
      .y(function(d) { return d.value })
      .yDomain([0, #{@transaction_type_max_value}])
      .showValues(true)
      .staggerLabels(true)
      .valueFormat(d3.format('$,f'))
      .margin({top: 30, right: 60, bottom: 50, left: 70})
      .color(d3.scale.category10().range());

    chart.yAxis.axisLabel("Amount")
      .tickFormat(d3.format('$,f'));


    d3.select('svg.transaction_type')
      .datum(data)
      .transition().duration(500)
      .call(chart);

    nv.utils.windowResize(chart.update);

    return chart;
  });

h4 Campaign Finance Transactions

svg.transactions style='height:600px; width:690px;'

javascript:

  function formatAnalyticsData() {
    var data = #{@stats_for_chart.to_json.html_safe}

    return $.map(data, function(k) {
      return {
        key: k.key,
        values: $.map(k.values, function(v) {
          return {
            x: new Date(v.x),
            y: v.y
          }
        })
      }
    })
  }

  nv.addGraph(function() {
    var chart = nv.models.lineChart()
      .margin({top: 30, right: 60, bottom: 50, left: 70})
      .useInteractiveGuideline(true)
      .color(d3.scale.category10().range());

    chart.xAxis.axisLabel("Date")
      .tickFormat(function(d) {
        return d3.time.format('%b %d')(new Date(d));
      });

    chart.yAxis.axisLabel("Amount")
      .tickFormat(d3.format('$,f'));

    d3.select('svg.transactions')
      .datum(formatAnalyticsData)
      .transition().duration(500)
      .call(chart);

    nv.utils.windowResize(chart.update);

    return chart;
  });

table.table.table-bordered.table-hover
  thead
    tr
      th Date
      th Status
      th Filer
      th Contributor / Payee
      th Type
      th State
      th Amount
      th Aggregate Amount

  tbody
    - @candidate_transactions.each do |trans|
      tr
        td = trans.transaction_date
        td = trans.transaction_status
        td = trans.filer
        td = trans.contributor_payee
        td = trans.sub_type
        td = trans.state
        td = number_to_currency trans.amount
        td = number_to_currency trans.aggregate_amount

br